// <auto-generated />
namespace NRWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class Starter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Starter));
        
        string IMigrationMetadata.Id
        {
            get { return "201311102055577_Starter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
